{% set version = "2.2.1" %}

package:
  name: zlib-ng
  version: {{ version }}

source:
  url: https://codeload.github.com/zlib-ng/zlib-ng/tar.gz/refs/tags/{{ version }}
  sha256: ec6a76169d4214e2e8b737e0850ba4acb806c69eeace6240ed4481b9f5c57cdf
  fn: zstd-ng.tar.gz

build:
  number: 0
  run_exports:
    # Just guessing since th library is so new
    # but they seem to want to be backward compatible
    # https://abi-laboratory.pro/index.php?view=timeline&l=zlib-ng
    - {{ pin_subpackage('zlib-ng', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:

test:
  commands:
    - test -e $PREFIX/include/zlib-ng.h                         # [unix]
    - test -e $PREFIX/include/zconf-ng.h                        # [unix]
    - test -e $PREFIX/lib/libz-ng${SHLIB_EXT}                   # [unix]
    - test -e $PREFIX/lib/pkgconfig/zlib-ng.pc                  # [unix]
    - if not exist %LIBRARY_INC%\zlib-ng.h exit 1               # [win]
    - if not exist %LIBRARY_INC%\zconf-ng.h exit 1              # [win]
    - if not exist %LIBRARY_BIN%\zlib-ng2.dll exit 1            # [win]
    - if not exist %LIBRARY_LIB%\zlib-ng.lib exit 1.            # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\zlib-ng.pc exit 1    # [win]

about:
  home: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems

extra:
  recipe-maintainers:
    - hmaarrfk
