{% set version = "2.3.2" %}
# Obtain from ZLIB_VERSION in zlib.h.in; https://github.com/zlib-ng/zlib-ng/blob/VERSION/zlib.h.in#L61
{% set zlib_api = "1.3.1" %}
{% set number = 0 %}

package:
  name: zlib-ng-split
  version: {{ version }} # [compat == "0"]
  version: {{ zlib_api }} # [compat == "1"]

source:
  url: https://codeload.github.com/zlib-ng/zlib-ng/tar.gz/refs/tags/{{ version }}
  sha256: 6a0561b50b8f5f6434a6a9e667a67026f2b2064a1ffa959c6b2dae320161c2a8
  fn: zstd-ng.tar.gz

build:
  number: {{ number }}
  string: h{{ PKG_HASH }}_ng_{{ version.replace(".", "") }}_{{ number }}  # [compat == "1"]
  run_exports:
    # Just guessing since the library is so new
    # but they seem to want to be backward compatible
    # https://abi-laboratory.pro/index.php?view=timeline&l=zlib-ng
    - {{ pin_subpackage('zlib-ng', max_pin='x.x') }}  # [compat == "0"]
    - {{ pin_subpackage('zlib', max_pin='x') }}  # [compat == "1"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make  # [unix]
  host:

outputs:
{%- if compat == "0" %}
  - name: zlib-ng
{%- else %}
  - name: zlib
  - name: libzlib
    version: {{ zlib_api }}
    build:
      string: h{{ PKG_HASH }}_ng_{{ number }}
      run_exports:
        - {{ pin_subpackage('libzlib', max_pin='x') }}
      track_features:
        - zlib-ng-compat
    requirements:
      run:
        - zlib {{ zlib_api }} *_ng_{{ version.replace(".", "") }}_{{ number }}
{%- endif %}

test:
  commands:
  {%- if compat == "0" %}
    - test -e $PREFIX/include/zlib-ng.h                         # [unix]
    - test -e $PREFIX/include/zconf-ng.h                        # [unix]
    - test -e $PREFIX/lib/libz-ng${SHLIB_EXT}                   # [unix]
    - test -e $PREFIX/lib/pkgconfig/zlib-ng.pc                  # [unix]
    - if not exist %LIBRARY_INC%\zlib-ng.h exit 1               # [win]
    - if not exist %LIBRARY_INC%\zconf-ng.h exit 1              # [win]
    - if not exist %LIBRARY_BIN%\zlib-ng2.dll exit 1            # [win]
    - if not exist %LIBRARY_LIB%\zlib-ng.lib exit 1.            # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\zlib-ng.pc exit 1    # [win]
  {%- else %}
    - test -e $PREFIX/include/zlib.h                            # [unix]
    - test -e $PREFIX/include/zconf.h                           # [unix]
    - test -e $PREFIX/lib/libz${SHLIB_EXT}                      # [unix]
    - test -e $PREFIX/lib/pkgconfig/zlib.pc                     # [unix]
    - if not exist %LIBRARY_INC%\zlib.h exit 1                  # [win]
    - if not exist %LIBRARY_INC%\zconf.h exit 1                 # [win]
    - if not exist %LIBRARY_BIN%\zlib1.dll exit 1               # [win]
    - if not exist %LIBRARY_LIB%\zlib.lib exit 1                # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\zlib.pc exit 1       # [win]
  {%- endif %}

about:
  home: https://github.com/zlib-ng/zlib-ng
  dev_url: https://github.com/zlib-ng/zlib-ng
  license: Zlib
  license_family: Other
  license_file: LICENSE.md
  summary: zlib data compression library for the next generation systems

extra:
  feedstock-name: zlib-ng
  recipe-maintainers:
    - hmaarrfk
    - mgorny
